substitutions:
  devicename: "gecko-controller"
  friendly_name: "Gecko spa controller "
  device_description: "Controller interface for Gecko spa"
  
esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

logger:
  level: DEBUG
  baud_rate: 0 # disable logging over uart

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome

web_server:

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: "${device_description}"

external_components:
  # - source: github://dala318/esphome-gecko
  - source:
      type: local
      path: components

i2c:
  id: i2c_bus
  sda: GPIO14
  scl: GPIO15

gecko:
  i2c_id: i2c_bus
  address: 0x48

sensor:
  - platform: gecko
    id: temp
    name: Temperature
    sensor_id: temperature  # Just some temporary stuff, to be replaced by some enum
    update_interval: 5s
