substitutions:
  devicename: "i2c-listener"
  friendly_name: "Generic I2C listener "
  device_description: "Sniffs I2C SDA and SCL pins for data"
  
esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

logger:
  # level: INFO
  level: DEBUG
  # baud_rate: 0 # disable logging over uart

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome

web_server:

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: "${device_description}"
  # platformio_options:
  #   build_flags: 
  #     - -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768

external_components:
  # - source: github://dala318/esphome-gecko
  - source:
      type: local
      path: components

i2c:
  id: i2c_bus
  sda: GPIO14
  scl: GPIO15

i2c_listener:
  i2c_id: i2c_bus
  address: 0x00
  port: 6638
  buffer_size: 256

binary_sensor:
  - platform: i2c_listener
    connected:
      name: Connected

sensor:
  - platform: i2c_listener
    connection_count:
      name: Number of connections

# text_sensor:
#   - platform: i2c_listener
#     dump_data:
#       name: Last data from I2C